In [1]:
import numpy as np

In [70]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [33]:
negative_num = a[a < 0]

In [34]:
negative_num.shape

(4,)

2. How many positive numbers are there?

In [35]:
positive_num = a[(a > 0)]

In [36]:
positive_num.shape

(5,)

3. How many even positive numbers are there?

In [37]:
positive_even = a[(a > 0) & (a % 2 == 0)]

In [38]:
positive_even.shape

(3,)

4. If you were to add 3 to each data point, how many positive numbers would there be?


In [95]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a = a + 3

In [96]:
a[a > 0].shape

(10,)

5. If you squared each number, what would the new mean and standard deviation be?


In [97]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a.mean()


3.0

In [98]:
a.std()

8.06225774829855

In [99]:
squared = a ** 2
squared.mean()

74.0

In [100]:
squared.std()

144.0243035046516

6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.


In [51]:
new_mean = a - a.mean() 

new_mean.mean()

0.0

In [52]:
m = np.array(new_mean)

In [53]:
m

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [54]:
m.mean()

0.0

7. Calculate the z-score for each data point. Recall that the z-score is given by:

In [56]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

z_score = (a - a.mean()) / a.std()
# z_score = (m / a.std())

In [57]:
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [111]:
import numpy as np

Life w/o numpy to life with numpy

 - Use python's built in functionality/operators to determine the following:


In [139]:
# Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [120]:
sum_of_a = sum(a)

sum_of_a

55

Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [123]:
min_of_a = min(a)
min_of_a

1

Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [122]:
max_of_a = max(a)
max_of_a

10

Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [128]:
mean_of_a = sum(a) / len(a)
mean_of_a

5.5

Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [156]:
product_of_a = 1

for x in a:
    product_of_a *= x
print(product_of_a)
     
 

3628800


Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [166]:
squares_of_a = []

for x in a:
        squares_of_a.append(x ** 2)
print(squares_of_a)    
    

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [176]:
odds_in_a = []

for x in a:
    if (x % 2 == 1):
        odds_in_a.append(x)    
print(odds_in_a)             

[1, 3, 5, 7, 9]


Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [177]:
evens_in_a = []

for x in a:
    if (x % 2 == 0):
        evens_in_a.append(x)    
print(evens_in_a) 

[2, 4, 6, 8, 10]


What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
 - Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.


In [59]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]
b = np.array(b)

Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**


In [60]:
    np.sum(b)

33

In [61]:
np.min(b)

3

In [62]:
np.max(b)

8

In [187]:
np.mean(b)

5.5

In [188]:
np.product(b)

20160

In [63]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [64]:
odds_b = b[b % 2 == 1]

odds_b

array([3, 5, 7])

In [65]:
b = np.array(b)

even_b = b[b % 2 == 0]

even_b

array([4, 6, 8])

Exercise 9 - print out the shape of the array b.

Exercise 10 - transpose the array b.

Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)


In [219]:
b.shape

(2, 3)

In [226]:
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [68]:
b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [69]:
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
Exercise 1 - Find the min, max, sum, and product of c.

Exercise 2 - Determine the standard deviation of c.

Exercise 3 - Determine the variance of c.

Exercise 4 - Print out the shape of the array c

Exercise 5 - Transpose c and print out transposed result.

Exercise 6 - Get the dot product of the array c with c. 

Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [70]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]


c = np.array(c) 

In [71]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.min(c)

1

In [73]:
np.max(c)

9

In [74]:
np.sum(c)

45

In [75]:
np.product(c)

362880

In [76]:
round(np.std(c), 3)

2.582

In [77]:
round(np.var(c), 3)

6.667

In [78]:
c.shape

(3, 3)

In [80]:
ct = c.transpose()

ct

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [88]:
dot_product = np.dot(c, c)

dot_product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
product_of_c_ct = np.multiply(c, ct)

np.sum(product_of_c_ct)

261

In [46]:
np.product(product_of_c_ct)

131681894400

Setup 4

d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

Exercise 1 - Find the sine of all the numbers in d

Exercise 2 - Find the cosine of all the numbers in d

Exercise 3 - Find the tangent of all the numbers in d

Exercise 4 - Find all the negative numbers in d

Exercise 5 - Find all the positive numbers in d

Exercise 6 - Return an array of only the unique numbers in d.

Exercise 7 - Determine how many unique numbers there are in d.

Exercise 8 - Print out the shape of d.

Exercise 9 - Transpose and then print out the shape of d.

Exercise 10 - Reshape d into an array of 9 x 2

In [84]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)

In [85]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [87]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [28]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [29]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [31]:
d[d < 0]

array([-90, -30, -45, -45])

In [32]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [36]:
d_unique = np.unique(d)

d_unique

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [37]:
d_unique.shape

(11,)

In [38]:
d.shape

(3, 6)

In [89]:
d_transposed = np.transpose(d)

d_transposed.shape

(6, 3)

In [45]:
d = d.reshape([9, 2])

d

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])